### PR TITLE
support for encrypted private key ssh authentication

### PR DESCRIPTION
**Pull request by cmhe**
~~This also renames the 'key' property to 'key_file', so that the new 'key' property can contain a `PKey` object.~~ (No longer part of this PR)

### CODE REVIEW

**Comment by cmhe** [comment]
This PR currently has some issues:

- [ ] mypy type errors
- [ ] `Authenticator` objectes aren't reused, so password it asked everytime the initialization routine runs.

**Comment by Rahix** [comment]
Hello Claudius, thanks for your PR, I will take a look shortly :)

**Comment by Rahix** [comment]
Ok, if you look at the travis log, it looks like you haven't run `black` on your source code (it should run automatically if you run the `pre-commit` config).  If you do this, I will fix the rest ;)

**Comment by Rahix** [comment]
Hmm, I just noticed something ... Your code obviously needs a prompt to query the user for his ssh-key's password.  This is something not really desirable in *tbot* as it means, *tbot* might hang if run in an automated environment.  I don't think it is a good idea to have such "automatic" prompts happening by default ... The alternative, to store the password in the config file is also really bad.  I'd suggest using ssh-agent instead?  Personally, I have just created a new key for tbot which does not require a password, but if that doesn't suit you, I think ssh-agent would be the better solution ...

**Comment by Rahix** [comment]
While browsing your fork, I stumbled upon this commit: `47d8c591554f3571e6c99b9f520146dcb7bcb0f2`

I really like this! Would you mind opening a separate pull request for it?

**Pull request closed without merging**
