### PR TITLE
newbot: Add --log option to newbot CLI.

### PR DESCRIPTION
**Pull request by locomotiveviaduct**
Signed-off-by: Mark A <mkand@microsoft.com>

resolves https://github.com/Rahix/tbot/issues/80

### CODE REVIEW

**Comment by locomotiveviaduct** [comment]
resolves https://github.com/Rahix/tbot/issues/80

**Review by Rahix — COMMENTED** [review]
Hi, thanks a lot for the PR.

When I added `newbot`, I intentionally did not add back the `--log` argument as my plan was/is to replace the logging system with a new one.  The existing logging implementation is quite bad for what people need it to do, it is usually better to just "log" the stdout from `newbot` as it contains more valuable information in a lot of cases.

If your usecase is test-result reporting, I would actually switch away from  the `newbot` interface entirely and go with `pytest` instead as detailed here: [pytest Integration](https://tbot.tools/pytest.html)

That said, I can see how some people would like to still access the existing logging through `newbot` anyway.  My suggestion is that we name the CLI flag something else so `--log` stays free for whatever comes to replace the current logging.

What about `--legacy-log`?  Or if that suggests too much that a new implementation already exists, what about `--json-log-stream`?

---

Beyond this, a slightly different topic:  I am thinking about relicensing (parts of) tbot in the near future.  You probably know how painful this can get for open-source projects...  So it may be better to ask upfront:  Would it be possible for you to give me written permission to relicense your contribution(s) under one or more of the [OSI approved licenses](https://opensource.org/licenses/alphabetical) in the future?

**Comment by locomotiveviaduct** [comment]
Thanks for the response.

We use _--log_ in our existing tbot invocations, so it would be helpful to minimize the disruption in migrating to newbot.  Renaming the option to something like _--legacy-log_ or _--json-log-stream_ sounds reasonable.

Can I get back to you on the license part of your question?

**Comment by Rahix** [comment]
> We use --log in our existing tbot invocations, so it would be helpful to minimize the disruption in migrating to newbot.

Yeah, this is what I was thinking.

> Can I get back to you on the license part of your question?

Sure, sorry for this...

**Review by Rahix — APPROVED** [review]
Code looks good, I will wait for your reply on the other topic :)

**Comment by locomotiveviaduct** [comment]
I've spoken to our legal folks, and you have permission to sublicense the contribution under GPLv3 later under an OSI license of your choice.

Thanks for waiting.

**Comment by Rahix** [comment]
Alright, thank you very much!

**Pull request merged**
